spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-url: http://localhost:8080/login/oauth2/code/google
            client-secret: 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
            client-id: 737182155708-e9vgbl5b9on3rli2712m8m7q2jn73ep5.apps.googleusercontent.com
            scope: profile,email
        provider:
          kakao:
            tokenUri: https://kauth.kakao.com/oauth/token
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            userNameAttribute: id
            userInfoUri: https://kapi.kakao.com/v2/user/me
  profiles:
    include: oauth
  datasource:
    password: '1234'
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/Art1st?autoReconnect=true
