server:
    port: 8080 # ?? ?? ????
    servlet:
      session:
          timeout: 30m

spring:
    security:
      oauth2:
        client:
          registration:
            google:
              #redirect-uri: http://localhost:8080/login/oauth2/code/google
              client-id: 737182155708-e9vgbl5b9on3rli2712m8m7q2jn73ep5.apps.googleusercontent.com
              client-secret: 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
              scope:
                - profile
                - email
            kakao:
              client-id: 429af9b6dc56e35d3979f754e3e3dd53
              client-secret: ALCV30N0sZUZwcKze7GwK87jvQDL5DLS
              client-name: Kakao
              client-authentication-method: client_secret_post
              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
              authorization-grant-type: authorization_code
              scope:
                - profile_nickname
                - account_email
            naver:
              client-id: nTMnHNwxHqGi1Vt1AJ3j
              client-secret: 6FWWQL4GkW
              client-name: Naver
              redirect-uri: http://localhost:8080/login/oauth2/code/naver
              authorization-grant-type: authorization_code
              scope:
                - name
                - email
          provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response
            kakao:
              authorizationUri: https://kauth.kakao.com/oauth/authorize
              tokenUri: https://kauth.kakao.com/oauth/token
              userInfoUri: https://kapi.kakao.com/v2/user/me
              userNameAttribute: id
    # H2 Database ??
    datasource:
        driver-class-name: org.h2.Driver
        url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
        #url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
        username: user        # H2 DB ?? ID (??? ??)
        password: 1234        # H2 DB ?? PW (??? ??)

    # H2 Console ??
    h2:
        console: # H2 DB? ??? ??? ? ?? ??
            enabled: true           # H2 Console ?? ??
            path: /h2-console       # H2 Console ?? ??

    # JPA ??
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create        # DB ??? ?? (none, create, create-drop, update, validate)
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true      # ?? ?? ?? (??)
                show_sql: true        # ?? ?? ??

#    config:
#        import: config.yml